/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

//
function go(){
    var checkIfEven = function(aNumber){
        if(aNumber % 2 === 0){
            return true;
        }
        else{
            return false;
        }
    }

    var findFiboNumbersBelow = function(maxNumber){
        var fiboArray = [1, 2];
        var sumOfEvens = 0;
        var i = 1;
        while (fiboArray[i] < maxNumber){
            if(checkIfEven(fiboArray[i])){
                sumOfEvens += fiboArray[i];
            }

            i++;
            //find next fibo number
            fiboArray[i] = fiboArray[i-1] + fiboArray[i-2];
        }
        return sumOfEvens;
    }

    var yourMaxNumber = prompt("Enter a max number");
    var theSum = findFiboNumbersBelow(yourMaxNumber);
    document.write(theSum);
}

